---
- hosts: devops
  user: sre
  become: yes
  connection: ssh
  tasks:
    - name: Installation HTTPD
      action: yum name=httpd state=present
    - name: Installation Git
      action: yum name=git state=present
    - name: Start HTTPD Service
      action: service name=httpd state=started
